### ISSUE TITLE
Audio Not audible

### ISSUE THREAD

**Issue by Taserwebs** [krreet/plugin.video.jiotv#67]
Some of the Channels Audio is not playing only the video is playing

**Comment by Karveanjali** [comment]
Ok. I did some research. 451 error happens when contents are Unavailable as blocked by ISP for Legal Reasons.
Fix - I was using a VPN software with  server1 (VPN provides multiple servers for a country) and 451 error was coming up.. using same VPN software I switched to server2 and boom.. started to work !!
I verified by doing trial&error by connecting to different servers. Reconnected to server1.. 451 error repeated… switched to server2.. works perfectly 
Conclusion- try different India based VPN servers.. one of those should work !!

**Comment by KriezParker** [comment]
Hi @Karveanjali Can you able to hear audio which has multi audio. Ex: Pogo Channel.

**Comment by KriezParker** [comment]
@Karveanjali Is multi audio working for you.. Ex: Pogo Channel

**Comment by Karveanjali** [comment]
Audio for Pogo doesn’t work😕.. trying some options .. will let you know if anything makes it work

**Comment by KriezParker** [comment]
@Karveanjali Thank you 😊

**Comment by rockynel** [comment]
Thank you sir for your suggestion 🙏

**Comment by technofreak24** [comment]
Audio Issue on multiple language channels is due to *Inputstream Adaptive* bug, that can be solved by downgrading/upgrading to a correct version.
*Multiple Language Audio* are Playing okay now with correct versions of *Inputstream Adaptive*.
![Screenshot_20230413-201338](https://user-images.githubusercontent.com/121749085/231798248-391ce9cd-fc71-403b-a598-95a30230d69c.png)

**Comment by technofreak24** [comment]
![screenshot00003_122348](https://user-images.githubusercontent.com/121749085/231798760-d3503c28-73a0-45eb-bf4e-30078d1a9896.png)

![screenshot00007_081127](https://user-images.githubusercontent.com/121749085/231798850-c24094a6-1434-4c48-9ec3-d650b0446942.png)

![screenshot00000_081509](https://user-images.githubusercontent.com/121749085/231798938-18d8158a-3d38-4398-8b26-d86526513f74.png)

**Comment by Taserwebs** [comment]
@technofreak24 can you give me the latest jiotv plugin update link

**Comment by Taserwebs** [comment]
@technofreak24 can you give me your's after you have edited to fix all the bugs and errors?

**Comment by Taserwebs** [comment]
@Karveanjali  can you tell me the vpn app please it will be useful, thanks

**Comment by Karveanjali** [comment]
VPN - Surfshark 
Delhi server

**Comment by Taserwebs** [comment]
@technofreak24 how to change the input stream adaptive version in kodi to get audio audible?

**Comment by technofreak24** [comment]
Go to page [InputStream Adaptive add-on for Kodi ](https://github.com/xbmc/inputstream.adaptive/releases) and download older version like the older version zip like [20.3.2-Nexus](https://github.com/xbmc/inputstream.adaptive/releases/tag/20.3.2-Nexus)
In the Kodi Add-on Browser and install the older version zip like [20.3.2-Nexus](https://github.com/xbmc/inputstream.adaptive/releases/tag/20.3.2-Nexus)

**Comment by Taserwebs** [comment]
@technofreak24 iam using kodi version 19.5 how should i install inputstream Adaptive add-on ?

**Comment by tobalan** [comment]
check 2.3.4 with fixes
