### ISSUE TITLE
Plugin Not working AGAIN..

### ISSUE THREAD

**Issue by djpareta** [krreet/plugin.video.jiotv#74]
Hello Devs,

Jio TV Plugin is not working Again, Please check and Update it..

**Comment by djpareta** [comment]
current version using is 2.0.26

**Comment by technofreak24** [comment]
Plugin [v2.0.25](https://github.com/krreet/plugin.video.jiotv/releases/tag/v2.0.25) is working great.
You have to Logout and Login Again !
Now the multi-audio channels are also working perfectly from last 3 days.
We all have checked in group.

**Comment by djpareta** [comment]
Thanks

**Comment by technofreak24** [comment]
**KODI Web Remote Control Options**

Please add the following options in python code so that the add-on settings can be controlled by **KODI Web Remote Control** on mobile phone browser.

![1685778640731_012205](https://github.com/krreet/plugin.video.jiotv/assets/121749085/e1d5c206-9901-40bf-9fe1-d497543ff5d5)

![Screenshot_2023-06-05-22-04-47-569_org mozilla firefox_beta_100532](https://github.com/krreet/plugin.video.jiotv/assets/121749085/f43ca91e-203d-4180-b644-a20c5c3ce321)

![Screenshot_2023-06-05-21-28-32-338_org mozilla firefox_beta_092919](https://github.com/krreet/plugin.video.jiotv/assets/121749085/ac50fcbe-4be3-4946-8bee-d0066c0dbc09)

**Comment by tobalan** [comment]
check 2.3.4 with fixes
